#! /bin/sh -e
# $Id: setup,v 1.1 2003/01/06 22:56:11 jsr Exp $
#
# This script builds the files necessary to configure this package for
# development.  Once you run this script, you will need GNU make,
# autoconf, and automake to build the software.  You must run "make
# dist" if you the wish to create a source tree that can be built
# without these tools.
#
if test ! -f configure.in; then
	echo Must run this from source directory >&2
	exit 1
fi

set -x
chmod +x setup
aclocal
autoheader
automake --add-missing
autoconf
set +x

if test -f config.status; then
    set -x
    sh config.status
fi
