CFLAGS =  -g
CC   = gcc
GET  = 
REL  = 
SRCS = event.c misc.c util.c node.c find.c event_types.c sim.c join.c in.c stabilize.c doc.c
OBJS = event.o misc.o util.o node.o find.o event_types.o sim.o join.o in.o stabilize.o doc.o

INCLUDE_FILES = def.h node.h event.h event_types.h fun.h

sim: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o sim -lm -ll
depend: 
	makedepend $(CFLAGS) $(SRCS)
clean: 
	rm *.o
sources: $(SRCS)

# DO NOT DELETE THIS LINE -- make depend depends on it.


doc.o: def.h event.h event_types.h fun.h incl.h node.h /usr/include/alloca.h
doc.o: /usr/include/bits/endian.h /usr/include/bits/pthreadtypes.h
doc.o: /usr/include/bits/sched.h /usr/include/bits/select.h
doc.o: /usr/include/bits/sigset.h /usr/include/bits/types.h
doc.o: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
doc.o: /usr/include/endian.h /usr/include/features.h /usr/include/gnu/stubs.h
doc.o: /usr/include/stdlib.h /usr/include/sys/cdefs.h
doc.o: /usr/include/sys/select.h /usr/include/sys/sysmacros.h
doc.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/xlocale.h
doc.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stddef.h
doc.o: var.h
event.o: def.h event.h event_types.h fun.h incl.h node.h
event.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
event.o: /usr/include/bits/stdio_lim.h /usr/include/bits/types.h
event.o: /usr/include/bits/wchar.h /usr/include/features.h
event.o: /usr/include/_G_config.h /usr/include/gconv.h
event.o: /usr/include/gnu/stubs.h /usr/include/libio.h /usr/include/malloc.h
event.o: /usr/include/stdio.h /usr/include/sys/cdefs.h /usr/include/wchar.h
event.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stdarg.h
event.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stddef.h
event.o: var.h
event_types.o: def.h event.h event_types.h fun.h incl.h node.h var.h
find.o: def.h event.h event_types.h fun.h incl.h node.h var.h
in.o: def.h event.h event_types.h fun.h incl.h node.h
in.o: /usr/include/bits/endian.h /usr/include/bits/pthreadtypes.h
in.o: /usr/include/bits/sched.h /usr/include/bits/stdio_lim.h
in.o: /usr/include/bits/types.h /usr/include/bits/wchar.h /usr/include/ctype.h
in.o: /usr/include/endian.h /usr/include/features.h /usr/include/_G_config.h
in.o: /usr/include/gconv.h /usr/include/gnu/stubs.h /usr/include/libio.h
in.o: /usr/include/malloc.h /usr/include/stdio.h /usr/include/sys/cdefs.h
in.o: /usr/include/wchar.h /usr/include/xlocale.h
in.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stdarg.h
in.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stddef.h
in.o: var.h
join.o: def.h event.h event_types.h fun.h incl.h node.h /usr/include/alloca.h
join.o: /usr/include/bits/endian.h /usr/include/bits/pthreadtypes.h
join.o: /usr/include/bits/sched.h /usr/include/bits/select.h
join.o: /usr/include/bits/sigset.h /usr/include/bits/types.h
join.o: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
join.o: /usr/include/endian.h /usr/include/features.h /usr/include/gnu/stubs.h
join.o: /usr/include/stdlib.h /usr/include/sys/cdefs.h
join.o: /usr/include/sys/select.h /usr/include/sys/sysmacros.h
join.o: /usr/include/sys/types.h /usr/include/time.h /usr/include/xlocale.h
join.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stddef.h
join.o: var.h
misc.o: def.h event.h event_types.h fun.h incl.h node.h var.h
node.o: def.h event.h event_types.h fun.h incl.h node.h
node.o: /usr/include/bits/endian.h /usr/include/bits/huge_val.h
node.o: /usr/include/bits/mathcalls.h /usr/include/bits/mathdef.h
node.o: /usr/include/bits/nan.h /usr/include/bits/pthreadtypes.h
node.o: /usr/include/bits/sched.h /usr/include/bits/stdio_lim.h
node.o: /usr/include/bits/types.h /usr/include/bits/wchar.h
node.o: /usr/include/endian.h /usr/include/features.h /usr/include/_G_config.h
node.o: /usr/include/gconv.h /usr/include/gnu/stubs.h /usr/include/libio.h
node.o: /usr/include/malloc.h /usr/include/math.h /usr/include/stdio.h
node.o: /usr/include/sys/cdefs.h /usr/include/wchar.h
node.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/float.h
node.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stdarg.h
node.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stddef.h
node.o: var.h
sim.o: def.h event.h event_types.h fun.h incl.h node.h
sim.o: /usr/include/bits/endian.h /usr/include/bits/pthreadtypes.h
sim.o: /usr/include/bits/sched.h /usr/include/bits/stdio_lim.h
sim.o: /usr/include/bits/types.h /usr/include/bits/wchar.h
sim.o: /usr/include/ctype.h /usr/include/endian.h /usr/include/features.h
sim.o: /usr/include/_G_config.h /usr/include/gconv.h /usr/include/gnu/stubs.h
sim.o: /usr/include/libio.h /usr/include/malloc.h /usr/include/stdio.h
sim.o: /usr/include/sys/cdefs.h /usr/include/wchar.h /usr/include/xlocale.h
sim.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stdarg.h
sim.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stddef.h
sim.o: var.h
stabilize.o: def.h event.h event_types.h fun.h incl.h node.h
stabilize.o: /usr/include/alloca.h /usr/include/bits/endian.h
stabilize.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
stabilize.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
stabilize.o: /usr/include/bits/types.h /usr/include/bits/waitflags.h
stabilize.o: /usr/include/bits/waitstatus.h /usr/include/endian.h
stabilize.o: /usr/include/features.h /usr/include/gnu/stubs.h
stabilize.o: /usr/include/stdlib.h /usr/include/sys/cdefs.h
stabilize.o: /usr/include/sys/select.h /usr/include/sys/sysmacros.h
stabilize.o: /usr/include/sys/types.h /usr/include/time.h
stabilize.o: /usr/include/xlocale.h
stabilize.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stddef.h
stabilize.o: var.h
util.o: def.h event.h event_types.h fun.h incl.h node.h
util.o: /usr/include/bits/endian.h /usr/include/bits/huge_val.h
util.o: /usr/include/bits/mathcalls.h /usr/include/bits/mathdef.h
util.o: /usr/include/bits/nan.h /usr/include/bits/pthreadtypes.h
util.o: /usr/include/bits/sched.h /usr/include/bits/stdio_lim.h
util.o: /usr/include/bits/types.h /usr/include/bits/wchar.h
util.o: /usr/include/endian.h /usr/include/features.h /usr/include/_G_config.h
util.o: /usr/include/gconv.h /usr/include/gnu/stubs.h /usr/include/libio.h
util.o: /usr/include/malloc.h /usr/include/math.h /usr/include/stdio.h
util.o: /usr/include/sys/cdefs.h /usr/include/wchar.h
util.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/float.h
util.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stdarg.h
util.o: /usr/sww/pkg/gcc-2.95.2/lib/gcc-lib/i686-pc-linux-gnu/2.95.2/include/stddef.h
util.o: var.h
