#!/usr/bin/perl -an

# depends on fact that zero-th successor and finger is self.

if (/^===/) {
    print;
    undef @me;
} else {
    @me = @F[8,9,10] if !defined(@me);
    $dist = ($F[8] - $me[0])**2 + ($F[9] - $me[1])**2;
    $dist = sqrt($dist);
    $dist += $F[10] + $me[2];

    printf "%3s %40s %-30s %5d %2d | %6d %6d | %5d | [%8d, %8d, %5d] (%4d) => %10.2f\n",
    	@F, $dist;
}
