#!/usr/bin/perl -an

# depends on fact that zero-th successor and finger is self.

if (/^===/) {
    print;
    undef @me;
} else {
    @me = @F[8,9,10] if !defined(@me);
    $dist = ($F[8] - $me[0])**2 + ($F[9] - $me[1])**2 + ($F[10] - $me[2])**2;
    $dist = sqrt($dist);

    printf "%3s %40s %-35s %5d %2d | %6d %6d | %6d | [%8d, %8d, %8d] => %10.2f\n",
    	@F, $dist;
}
