#!/usr/bin/env python

"""
Read in a simple file of the format
    epochtime	event	IP_address
where epochtime is an int, event is "join" or "fail" and IP_address is
something like "18.72.0.3" (such as generated by plupdown.py).
Generate a bunch of events corresponding to vnodes that might have
something to do with that plus a corresponding number of inserts.

We will still simulate by the "second".
"""

import sha
import sys
from utils import random_id, random_interval, make_chordID

def str2bigint(s):
    a = map(ord, s)
    v = 0L
    for d in a:
	v = v << 8
	v = v | d
    return v

inserted = {}
def random_blockid ():
    s = sha.sha("%d" % random_id ())
    id = str2bigint (s.digest ())
    while id in inserted:
	# Damn birthdays.
	s = sha.sha("%d" % random_id ())
	id = str2bigint (s.digest ())
    inserted[id] = 1
    return id


firsttime = None
lasttime  = 0
progname  = sys.argv.pop (0)

fh = open (sys.argv.pop (0))
try:
    maxblocks = int (sys.argv.pop (0))
except:
    maxblocks = 1000
try:
    size = int (sys.argv.pop (0))
except:
    size = 8192
try:
    nodesforjoin = int (sys.argv.pop (0))
except:
    nodesforjoin = 250

# Control the "rate" at which blocks are inserted.
mu_i	= maxblocks / 10
sd_i	= maxblocks / 20

count = 0
onode = 0
insertok = 0
for line in fh.readlines ():
    (t, e, ip) = line.strip ().split ()

    # normalize time
    t = int (t)
    if not firsttime:
	firsttime = t
	nnode = make_chordID (ip, 11977, 0)
    t = t - firsttime

    if e == 'join':
	count += 1
	onode = make_chordID (ip, 11977, 0)
    elif count > 0 and e == 'fail':
	count -= 1
    if count > nodesforjoin:
	insertok = 1

    if t != lasttime:
	if maxblocks > 0 and insertok > 0:
	    for nt in xrange(lasttime+1,t-1):
		# Insert a few blocks every now and then between
		# the last event and this one.
		ni = random_interval (mu_i, sd_i)
		while ni > 0 and maxblocks > 0:
		    print nt, "insert", nnode, random_blockid (), size
		    ni -= 1
		    maxblocks -= 1
	lasttime = t
    print t, e, make_chordID (ip, 11977, 0)
    nnode = onode

